### ISSUE TITLE
creating folders for nested files

### ISSUE THREAD

**Issue by navFooh** [Robert-W/grunt-ftp-push#17]
When you want to upload a file that's nested several folders deep, for example: 'scripts/vendor/requirejs/require.js', the containing folders are not created correctly.

In order to create the parent folders correctly, it seems you have to include:
```
src: [
	'scripts',
	'scripts/vendor',
	'scripts/vendor/requirejs',
	'scripts/vendor/requirejs/require.js'
]
```
Is this expected behavior or are there tricks to make this work correctly?

Cheers, Thijs

**Comment by Robert-W** [comment]
It should handle that automatically and you should not have to do anything special to make it work.  Which version are you on?
There was a bug in the older version which would cause that to error out and not upload but I believe it was resolved in recent builds.  If your on the latest version (0.2.6 I believe) and this is still happening I will take a look.

**Comment by navFooh** [comment]
I'm on 0.2.6, but seem to have that problem.
It works when the folders already exist on the server, but when I select a new folder as 'dest' and include:
```
src: [
	'scripts/vendor/requirejs/require.js'
]
```
I get:
![capture](https://cloud.githubusercontent.com/assets/394452/5731255/da5abd96-9b81-11e4-8b11-b8bfe236e824.JPG)

If I use:
```
src: [
	'scripts',
	'scripts/vendor',
	'scripts/vendor/requirejs',
	'scripts/vendor/requirejs/require.js'
]
```
I get:
![capture2](https://cloud.githubusercontent.com/assets/394452/5731284/21f7b6fe-9b82-11e4-89ce-b14cc89d1cf5.JPG)

Thanks for the quick response, would be great if you could have a look! Very nice and clean plugin otherwise.

**Comment by Robert-W** [comment]
Ok, Ill take a look and post here once I can find something.

**Comment by Robert-W** [comment]
Alright I think I have a fix for you, if your up for testing this patch out I will put the instructions below, if not, I plan on pushing to git later tonight and publishing to npm sometime tomorrow after some more testing so you can grab the latest from either once its pushed.

Here is the patch if your interested, in your node_modules directory, look for 
<code>grunt-ftp-push/tasks/ftp_push.js</code>
around line 102 in the ```createDirectoriesForDestination``` function

replace the following: 
<pre><code>
fileObjects.forEach(function (fileItem) {
  if (fileItem.dest) {
    // Prepare the destination, then push into array for processing
    preparedDestination = destination + normalizeDir(fileItem.dest);
    destinations.push(preparedDestination);
  }
});
</code></pre>

with this:
<pre><code>
fileObjects.forEach(function (fileItem) {
      if (fileItem.dest) {
        // Prepare the destination, then push into array for processing
        preparedDestination = destination + normalizeDir(fileItem.dest);
        destinations.push(preparedDestination);
      } else {
        // Prepare the destination, then push into array for processing
        preparedDestination = destination + normalizeDir(fileItem.path);
        destinations.push(preparedDestination);
      }
    });
</code></pre>

**Comment by navFooh** [comment]
Hi Robert, just tested it and works perfectly now. Thanks!

**Comment by Robert-W** [comment]
Great thanks  The patch is up now on npm.
