### ISSUE TITLE
Files created as folders

### ISSUE THREAD

**Issue by navFooh** [Robert-W/grunt-ftp-push#18]
Me again.. Noticed an issue in the new release.

With the same setup as issue #17, parent folders are now created correctly. But the uploaded file will be created as a folder on the server:

![image](https://cloud.githubusercontent.com/assets/394452/5746042/47edd0fe-9c2d-11e4-97a0-d0df16a99dda.png)

Then it fails to write the file itself.

**Comment by Robert-W** [comment]
Is this version 3.0,   I noticed this same behavior on my initial patch but then made some changes and it worked on my side  If you are on 3.0 I will look again but that looks like the results from 2.8.


![screen shot 2015-01-14 at 3 06 36 pm](https://cloud.githubusercontent.com/assets/1177959/5746634/01a4f740-9bff-11e4-9033-42e50b48af97.png)

**Comment by Robert-W** [comment]
lines 102 to 112 should look like below:

<pre><code>
fileObjects.forEach(function (fileItem) {
      if (fileItem.dest) {
        // Prepare the destination, then push into array for processing
        preparedDestination = destination + normalizeDir(fileItem.dest);
        destinations.push(preparedDestination);
      } else {
        // Prepare the destination, then push into array for processing
        preparedDestination = destination + fileItem.path;
        destinations.push(preparedDestination);
      }
    });
</code></pre>

the main part to look at is in the else, if it reads destination + normalizeDir(fileItem.path) then your on 2.8, it should read like below.
<code>preparedDestination = destination + fileItem.path;</code>

**Comment by navFooh** [comment]
You're right I'm on 0.2.8. I did an:
```npm update grunt-ftp-push --save-dev```
and it did update, so I assumed I was on the latest version.

I'll check out the latest one and confirm in a bit

**Comment by navFooh** [comment]
All working properly, thanks!

**Comment by Robert-W** [comment]
Awesome, good to hear, sorry about that.
