### ISSUE TITLE
Structure Remains

### ISSUE THREAD

**Issue by emalherbi** [Robert-W/grunt-ftp-push#21]
Hey There!

I would like to copy the files from "docs/_site" to "www/bla", but when copy the structure remains. 

Here is my code.
```javascript
    /* ftp push */
    ftp_push: {
      your_target: {
        options: {
          username: "xxx",
          password: "bbb",
          host: "ftp.yyyy.com",
          dest: "/www/bla/",
          port: 21
        },
        files: [{
          expand: true,
          cwd: 'docs/_site',
          src: [ '**' ]
        }]
      }
    }
```
in ftp:
www/bla/docs/_site/index.html

but it should be:
www/bla/index.html

**Comment by Robert-W** [comment]
Hey @emalherbi, it should be doing that, can you verify that you are on the latest version (0.3.2)?  

If you are and are still seeing this I will take a look as soon as I can.  I am at an esri developer conference through March 13th so I may not have a chance to look into it til then.

**Comment by emalherbi** [comment]
sorry man. I updated the package and now worked.

**Comment by Robert-W** [comment]
Awesome, great to hear.
