### ISSUE TITLE
Large file fails to transfer with "Error: Passive socket timeout"

### ISSUE THREAD

**Issue by iandevlin** [Robert-W/grunt-ftp-push#22]
When trying to transfer a large file (822MB) it constantly fails to transfer, aborting before it's finished with:
"<file> failed to transfer because Error: Passive socket timeout"

I have tried different values for the "keepAlive" setting (and also "timeout" which jsftp has), with the same results.

It works fine on smaller files.

Any ideas on what I might be able to change?

**Comment by Robert-W** [comment]
Hmm, I have not personally tested with a file that large.  I can try something this week and see what i can do.  It seems jsftp does have support for streaming data through sockets, using their getPutSocket method might help but Im not sure on a file that large.  With the current plugin I don't think there is anything to configure to make it work apart from updating the source to try using the getPutSocket method of jsftp.

**Comment by Robert-W** [comment]
Note for self: this may be helpful - https://github.com/sergi/jsftp/pull/35/files

**Comment by iandevlin** [comment]
Hi Robert, many thanks for your swift response! It's not the end of the world for me if this doesn't work, as I can still manually transfer the file over WinSCP and it doesn't need to be transferred that often.

I will try what you suggested though when I have a moment to do so.

Thanks again.

**Comment by Robert-W** [comment]
Ok sounds good.  I will go ahead and close this out for now and make a note to add the streaming option for large files.  Thanks.
