### ISSUE TITLE
Extra folders is being created when file provided cwd other than '.' or './

### ISSUE THREAD

**Issue by liuyuns** [Robert-W/grunt-ftp-push#23]
Assume we want to upload following file

files:[
          {expand: true,cwd: 'test/sub',src: ['**/*']}
]

and under test/sub we have one file: dummy.txt

The result is following:
1. dummy.txt --> dest
2. dest/test/sub, empty folders! we don't want this in my opinion.

**Comment by Robert-W** [comment]
Hi @liuyuns,

I'll take a look at this over the weekend and try to merge it.  Im pretty busy for the next few days with work and school but I would agree, empty folders getting pushed is pointless.  Just to make sure I am understanding you.

your local structure looks like this (assuming test is in the root where the Gruntfile is):
<b>test</b>
<b>test/sub</b>
<b>test/sub/dummy.txt</b>

You want something like this:
<b>dummy.txt</b>

But your getting this:
<b>dummy.txt</b>
<b>test</b> (empty directory)
<b>test/sub</b> (empty directory)

**Comment by liuyuns** [comment]
Hi Robert,
Thank you for the quick reply, yes, your understanding is exactly right :)

**Comment by Robert-W** [comment]
Ok great, Ill check it out over the weekend and if everything looks good Ill merge it and add this case to the unit tests which will be my new version.  Thanks
