### ISSUE TITLE
Auto-reconnect feature

### ISSUE THREAD

**Issue by mattcodez** [Robert-W/grunt-ftp-push#3]
At my place of work, we have regular connection issues while uploading via FTP. While we'd like to correct these issues at the root cause, we're currently tolerating it by allowing our FTP clients to lose their connection and then automatically reconnect. WinSCP does this and will pick up where it left off in the transfer queue. Grunt-ftp-deploy will just hang on a file (usually the first one), state successful transfer for the file and eventually die with "Fatal error: 421 Timeout (120 seconds): closing control connection". There are days where we don't have issues for whatever reason and ftp-push runs just great.

Would an auto-reconnect ability like what WinSCP and other GUI clients have be possible? Would this be primarily a change request for JSFTP? It doesn't appear that JSFTP has a concept of a file queue so I would guess ftp-push would need to at least take care of that part.

**Comment by Robert-W** [comment]
Closing this for now due to inactivity, have not seen a way to do this without modifying jsftp.  If this request comes back I will forward a feature request to jsftp and see if its something that can be implemented there.
