### ISSUE TITLE
Suggestion: use of node path module

### ISSUE THREAD

**Issue by rarila** [Robert-W/grunt-ftp-push#30]
I'd like to suggest using the [node path module](https://nodejs.org/api/path.html) (the ``path.posix`` part) sometime in some refactoring in the future (as I know we all are short of spare time).

I believe it could greatly simplifiy the path handling (``normalize()``, ``join()``, ``dirname()``, …) and make it more secure. E.g. I don't know if *grunt-ftp-push* would handle paths like ``/foo/./..///bar`` gracefully.

**Comment by Robert-W** [comment]
Probably would not handle that path gracefully (although I have not tried one like that so your guess is as good as mine).  I agree that this will simplify the path handling and would be a good addition.  I have a new branch on my local machine at home I have been meaning to push up which will have unit tests and I can include this in that one as well

**Comment by Robert-W** [comment]
the path module is in 0.4.0 and 0.4.1.  I have committed another update to master which should be released relatively soon as 0.4.2, and it uses path.posix instead of just path.  Closing this as it will be released soon.

**Comment by rarila** [comment]
:+1: Great to hear!

**Comment by rarila** [comment]
Works, thanks!
Could you please tag 0.4.2!

**Comment by Robert-W** [comment]
Yup will do, I'm gonna try to deploy it this week sometime while Im at school
