### ISSUE TITLE
Struggling with creating folders

### ISSUE THREAD

**Issue by D0rx** [Robert-W/grunt-ftp-push#35]
So I'm trying to move files from my local directory to my FTP-server, where the FTP has no dir-structure at the moment.

I've set 
`{...
dest:"./"},
files:[{
expand:true,
src:["**"]
}]`

As far as I've understood it, lacking folder structure will be created automatically, but when I try this out, I get `Error 553 Prohibited file name: css\style.css`

Any help would be greatly appreciated

**Comment by Robert-W** [comment]
It should create directories for you if they are not already created but I will try your configuration a little later tonight and see what it produces.  That error is not one I have seen very often, the only other time I heard of it was when someone was trying to push an ```.htaccess``` file to their server and there was server settings preventing hidden files from being pushed.

**Comment by Robert-W** [comment]
Ok so I just tried a similar configuration and things uploaded without any issue, Do you have any other server you can try the same configuration on and see if it works?  Im wondering if it's something with that particular server.

**Comment by D0rx** [comment]
Tested it on another server where it seems to be working as intended. Guess the server provider I'm using are a bit restrictive. Thanks for the quick reply!

**Comment by Robert-W** [comment]
Ok, no problem.
