### ISSUE TITLE
SFTP?

### ISSUE THREAD

**Issue by doodirock** [Robert-W/grunt-ftp-push#38]
Just wonders if SFTP is an option.  I didnt see anything within the list of options.

**Comment by Robert-W** [comment]
Hey sorry for the late reply, Ive been out with the flu this past week.  At the moment it is not supported.  Im using JSFTP for my ftp library and I don't think he supports it yet, there was a discussion here (https://github.com/sergi/jsftp/issues/39) but no clear resolution and I don't see anything in his docs mentioning support for it as of today.

This may be something supported in the future if anyone wants to contribute or I have time to find another ftp/sftp library that also supports syncing.
