### ISSUE TITLE
Does this work with FTPs TLS explicit?

### ISSUE THREAD

**Issue by JacobLett** [Robert-W/grunt-ftp-push#39]

**Comment by Robert-W** [comment]
I don't believe it does, It's just leveraging JSFTP and its functionality for all the FTP features.  So this plugin only supports things they have implemented.  I have seen a PR to merge in some basic functionality but nothing that would be useful for this plugin, See <a href='https://github.com/sergi/jsftp/pull/110'>https://github.com/sergi/jsftp/pull/110</a>

**Comment by JacobLett** [comment]
Thank you Robert. I am going to ask my server admin can just allow regular FTP since I am just creating sending theme files. Thank you for sharing this it really helps development.

**Comment by Robert-W** [comment]
Ok sounds good, and no problem.
