### ISSUE TITLE
Hide username and ftp details display via config

### ISSUE THREAD

**Issue by MythicAngel** [Robert-W/grunt-ftp-push#40]
When I used it in Travis-ci, I noticed that my ftpUsername and ftpHost was displayed in output log. It will be a nice inclusion if I can skip these entries automatically :-)

Great plugin :thumbsup:

**Comment by Robert-W** [comment]
Which tests are you running, none of my tests log any actual credentials? They just log dummy ones used to validate helper functions.

Im relatively new to Travis CI so Im not sure how to do something like this off the top of my head but those logs should only be visible when you log in.  I would have to read into Travis but I am not sure their is an easy way to hide those from the output, apart from maybe using Environment Variables.  If this is something you are familiar with and you wanna submit a Pull Request I can gladly take a look at it.

**Comment by MythicAngel** [comment]
Hi Robert,

I have created a pull request :-)
To understand this, please go to this build first: https://travis-ci.org/MythicAngel/BanglaDateJS/builds/101255653 and navigate to line 352~361. Here, ftpUsername (seorai7) and links are my personal ftp url and they are securely provided (and hidden) via environment settings in travis (line 84-86).

I have provided necessary comments about the pull request, please have a look...

**Comment by Robert-W** [comment]
Ahh ok, I see what you mean, sorry I misunderstood.  I'm at work at the moment but I will try to merge it in, add some documentation, and republish a new version tonight.  Thanks for pointing this out.
