### ISSUE TITLE
DeprecationWarning Ftp.rawquit: Use Ftp.raw('quit args') instead.

### ISSUE THREAD

**Issue by pavlovicnemanja** [Robert-W/grunt-ftp-push#50]
Getting warning
 (node:5508) DeprecationWarning: Ftp.raw[quit](args): Use Ftp.raw('quit args') instead.

:)

**Comment by Robert-W** [comment]
Thanks for pointing this out. If you have capacity to submit a PR I would appreciate it. Otherwise I will try to make the changes for this in the next few days.

**Comment by Psykoral** [comment]
I've added https://github.com/Robert-W/grunt-ftp-push/pull/51to resolve this issue.
